services:
  rl-worker:              # ── サービス名
    build: ./rl_worker    #   コンテキスト
    image: rl-worker
    command: tail -f /dev/null          # 常駐させる
    deploy:                             # (GPU 利用例)
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    volumes:
      - .:/workspace/minecraft-civ-ai
