version: "3.8"
services:
  rl-worker:
    build:
      context: ./rl_worker          # ← build コンテキストを rl_worker 以下に
      dockerfile: Dockerfile        # ← rl_worker/Dockerfile を使う
    volumes:
      - ./rl_worker:/app             # ホスト側のソースを /app にマウント
    environment:
      - DISPLAY=:99
    command: ["bash", "-c", "docker-entrypoint.sh && python train.py"]
  tensorboard:
    image: tensorflow/tensorflow
    ports:
      - "6006:6006"
    volumes:
      - ./logs:/workspace/logs
