services:
  rl-worker:
    image: ghcr.io/ahoudori77/minecraft-civ-ai/rl-worker:latest
    tty: true
    shm_size: 1g
    environment:
      WORLD: main-sim-001
      WORKER_ID: ${HOSTNAME:-worker-local}
      CUDA_VISIBLE_DEVICES: "0"
    volumes:
      - ./logs:/workspace/logs:rw
    command: python train.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
